### ISSUE TITLE
Error  API not healthy.

### ISSUE THREAD

**Issue by OmarZidan1997** [MarianoMolina/project_alice#8] opened 2024-10-19 13:00 UTC
Hi there,

Been using this project couple of days now, I love the work and the architecture behind project_alice.Seems pretty lit!

I do have problem to use some models even though I have configured my api through the interface.

```
Error: Required API embeddings is not healthy.

Traceback: Traceback (most recent call last):

File "/app/workflow/api_app/routes/task_execute.py", line 60, in execute_task_endpoint

result = await task.a_execute(api_manager=api_manager, **inputs)

File "/app/workflow/core/tasks/task.py", line 192, in a_execute

if self.required_apis and not self.validate_required_apis(kwargs.get("api_manager")):

File "/app/workflow/core/tasks/task.py", line 159, in validate_required_apis

raise ValueError(f"Required API {api_type} is not healthy.")

ValueError: Required API embeddings is not healthy.
```

I'm pretty sure I configured api key for the openai as I can use other tasks with it.

Any suggestion or perhaps pointing me somewhere to solve it :D 

thanks again for good project

// Omar

**Comment by MarianoMolina** [comment] 2024-10-23 12:42
Hey Omar. Really glad you are liking it. 

Really sorry for the delay in responding. I think I can imagine the issue, and I will need to fix it in the next update, but basically the problem is I didn't put the api 'health' field in the frontend for update, only the 'active', and when the api key isn't set in the environment it is created as "unhealthy", and even if you update it manually, it stays that way. 

The simplest solution I can think for you to fix this now, is to use MongoDB to view your database. You'll find the api collection, just find the problematic API and update the health field str. 

You'll find in your environment the address of the mongo db. 

I'll push an update with a few fixes in a few days, so you can wait and run the update.py script to simply get the fix when its ready. 

Cheers

**Comment by MarianoMolina** [comment] 2024-10-23 22:49
Pushed an update adding this prop to the frontend's Api flexible component, adding the health as a select. I've tested it and it seems to be working ok. Please run: 
- `python update.py` -> will rebuild with no cache
or do:
- `git pull` 
- `docker-compose down --rmi local`
- And then execute the run.bat -> although longer, this sequence will be a bit faster
Either sequence will update the containers. Let me know if you have other issues, and thank you for bringing this up.

**Comment by MarianoMolina** [comment] 2024-10-23 22:49
Closing until new developments.

**Closed by MarianoMolina** 2024-10-23 22:49 UTC
