### ISSUE TITLE
On large chat when context is above the limit of model Context size 

### ISSUE THREAD

**Issue by pentium10** [MarianoMolina/project_alice#18] opened 2024-12-12 09:11 UTC
When you chat a lot with an agent and context size goes above the set limit:

![image](https://github.com/user-attachments/assets/3ba87075-7949-43bf-8423-279701c75eaa)

This should inform the user nicely of >above context size, and not crash.

```
workflow-1      | INFO:     172.18.0.1:51836 - "POST /chat_response HTTP/1.1" 200 OK                                                                                                                              
workflow-1      | 2024-12-12 09:01:54,483 - root - WARNING - Invalid API data format for 6754cae9c1dd2545e92a172c - {'base_url': 'http://backend:3000/lm_studio'}
workflow-1      | 2024-12-12 09:01:54,484 - root - WARNING - Invalid API data format for 6754cae9c1dd2545e92a1740 - {'base_url': 'http://backend:3000/lm_studio'}
workflow-1      | 2024-12-12 09:01:54,485 - root - WARNING - Invalid API data format for 6754cae9c1dd2545e92a1768 - {'base_url': 'http://backend:3000/lm_studio'}                                                 
workflow-1      | 2024-12-12 09:01:54,486 - root - INFO - Generating LLM response                                                                                                                                 
workflow-1      | 2024-12-12 09:01:54,491 - root - WARNING - Estimated tokens (5247.0) exceed context size (4096) of model gemini-1.5-flash. Pruning. 
workflow-1      | 2024-12-12 09:01:54,493 - root - ERROR - Error generating response with API engine: 'coroutine' object is not iterable                                                                          
workflow-1      | 2024-12-12 09:01:54,495 - root - ERROR - Traceback (most recent call last):                                                                                                                     
workflow-1      |   File "/app/workflow/core/api/api_manager.py", line 142, in generate_response_with_api_engine                                                                                                  
workflow-1      |     return await engine_instance.generate_api_response(api_data=api_data, **kwargs)                                                                                                             
workflow-1      |   File "/app/workflow/core/api/engines/llm_engines/gemini_llm_engine.py", line 49, in generate_api_response
workflow-1      |     estimated_tokens = est_messages_token_count(messages, tools) + est_token_count(system)                                                                                                      
workflow-1      |   File "/app/workflow/util/text_splitters/utils/token_utils.py", line 11, in est_messages_token_count                                                                                           
workflow-1      |     total_tokens = sum(calculate_message_size(msg) / CHAR_PER_TOKEN for msg in messages)                                                                                                        
workflow-1      | TypeError: 'coroutine' object is not iterable                                                                                                                                                   
workflow-1      | 
workflow-1      | 2024-12-12 09:01:54,497 - root - ERROR - Error in turn execution: Error generating response with API engine: 'coroutine' object is not iterable                                                 
workflow-1      | Traceback (most recent call last):                                                                                                                                                              
workflow-1      |   File "/app/workflow/core/api/api_manager.py", line 142, in generate_response_with_api_engine                                                                                                  
workflow-1      |     return await engine_instance.generate_api_response(api_data=api_data, **kwargs)                                                                                                             
workflow-1      |   File "/app/workflow/core/api/engines/llm_engines/gemini_llm_engine.py", line 49, in generate_api_response                                                                                     
workflow-1      |     estimated_tokens = est_messages_token_count(messages, tools) + est_token_count(system)
workflow-1      |   File "/app/workflow/util/text_splitters/utils/token_utils.py", line 11, in est_messages_token_count                                                                                           
workflow-1      |     total_tokens = sum(calculate_message_size(msg) / CHAR_PER_TOKEN for msg in messages)                                                                                                        
workflow-1      | TypeError: 'coroutine' object is not iterable                                                                                                                                                   
workflow-1      |                                                                                                                                                                                                 
workflow-1      | During handling of the above exception, another exception occurred:                                                                                                                             
workflow-1      | 
workflow-1      | Traceback (most recent call last):                                                                                                                                                              
workflow-1      |   File "/app/workflow/core/chat/chat.py", line 330, in _execute_single_turn                                                                                                                     
workflow-1      |     llm_message = await self._generate_llm_response(                                                                                                                                            
workflow-1      |   File "/app/workflow/core/chat/chat.py", line 479, in _generate_llm_response                                                                                                                   
workflow-1      |     return await self.alice_agent.generate_llm_response(                                                                                                                                        
workflow-1      |   File "/app/workflow/core/agent/agent.py", line 215, in generate_llm_response                                                                                                                  
workflow-1      |     response_ref: References = await api_manager.generate_response_with_api_engine(
workflow-1      |   File "/app/workflow/core/api/api_manager.py", line 148, in generate_response_with_api_engine                                                                                                  
workflow-1      |     raise ValueError(f"Error generating response with API engine: {str(e)}")                                                                                                                    
workflow-1      | ValueError: Error generating response with API engine: 'coroutine' object is not iterable                                                                                                       
workflow-1      |                                                                                                                                                                                                 
workflow-1      | 2024-12-12 09:01:54,498 - root - ERROR - Error in turn 0: Error generating response with API engine: 'coroutine' object is not iterable                                                         
workflow-1      | Traceback (most recent call last):
workflow-1      |   File "/app/workflow/core/api/api_manager.py", line 142, in generate_response_with_api_engine                                                                                                  
workflow-1      |     return await engine_instance.generate_api_response(api_data=api_data, **kwargs)                                                                                                             
workflow-1      |   File "/app/workflow/core/api/engines/llm_engines/gemini_llm_engine.py", line 49, in generate_api_response                                                                                     
workflow-1      |     estimated_tokens = est_messages_token_count(messages, tools) + est_token_count(system)                                                                                                      
workflow-1      |   File "/app/workflow/util/text_splitters/utils/token_utils.py", line 11, in est_messages_token_count                                                                                           
workflow-1      |     total_tokens = sum(calculate_message_size(msg) / CHAR_PER_TOKEN for msg in messages)
workflow-1      | TypeError: 'coroutine' object is not iterable                                                                                                                                                   
workflow-1      |                                                                                                                                                                                                 
workflow-1      | During handling of the above exception, another exception occurred:                                                                                                                             
workflow-1      |                                                                                                                                                                                                 
workflow-1      | Traceback (most recent call last):                                                                                                                                                              
workflow-1      |   File "/app/workflow/core/chat/chat.py", line 301, in _execute_chat_turns                                                                                                                      
workflow-1      |     turn_message = await self._execute_single_turn(api_manager, all_generated_messages, user_data)
workflow-1      |   File "/app/workflow/core/chat/chat.py", line 330, in _execute_single_turn                                                                                                                     
workflow-1      |     llm_message = await self._generate_llm_response(                                                                                                                                            
workflow-1      |   File "/app/workflow/core/chat/chat.py", line 479, in _generate_llm_response                                                                                                                   
workflow-1      |     return await self.alice_agent.generate_llm_response(                                                                                                                                        
workflow-1      |   File "/app/workflow/core/agent/agent.py", line 215, in generate_llm_response                                                                                                                  
workflow-1      |     response_ref: References = await api_manager.generate_response_with_api_engine(
workflow-1      |   File "/app/workflow/core/api/api_manager.py", line 148, in generate_response_with_api_engine                                                                                                  
workflow-1      |     raise ValueError(f"Error generating response with API engine: {str(e)}")                                                                                                                    
workflow-1      | ValueError: Error generating response with API engine: 'coroutine' object is not iterable                                                                                                       
workflow-1      |                                                                                                                                                                                                 
workflow-1      | /app/workflow/core/chat/chat.py:322: RuntimeWarning: coroutine 'MessagePruner.prune' was never awaited                                                                                          
workflow-1      |   break                                                                                                                                                                                         
workflow-1      | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
workflow-1      | 2024-12-12 09:01:54,517 - root - ERROR - validation_response                                                                                                                                    
workflow-1      | INFO:     ('172.18.0.1', 51860) - "WebSocket /ws/a52c7619-9afc-4fd8-9da2-da71e617ce6d?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU0Y2FlOGMxZGQyNTQ1ZTkyYTE0M2EiLCJyb2xlIjoidXNlciIsImlhdCI6MTczMzg2MTM3MywiZXhwIjoxNzM2NDUzMzczfQ.nLM8395_fGPq_BRc1HCy3jSgRgD1K8V-69W16mOmlTQ" [accepted]                                                                                                       
workflow-1      | INFO:     connection open
workflow-1      | INFO:     connection closed                                                                                                                                                                     
workflow-1      | INFO:     127.0.0.1:46136 - "GET /health HTTP/1.1" 200 OK
```

**Comment by MarianoMolina** [comment] 2024-12-12 17:37
Oh wow, I literally found this issue this morning and fixed it. 

The problem is not that the context is too long (although I agree it should be visible for the user, I am adding that now), but that I missed an await on a method used to manage context overflow, which caused this crash. Normally it would be trying to reduce the context to avoid overflow. 

So on both accounts: this is fixed in the latest update. 
![image](https://github.com/user-attachments/assets/a02d29fa-077d-497c-924b-8a5edbcc8368)
![image](https://github.com/user-attachments/assets/95111c19-5b4d-4360-a272-c82f484557a6)

Thanks again for the feedback!

**Closed by MarianoMolina** 2024-12-12 17:37 UTC
